### ISSUE TITLE
'malloc' was not declared in this scope

### ISSUE THREAD

**Issue by mjkdz** [CoretechR/ESP32-WiFi-Robot#1]
'malloc' was not declared in this scope  error ！Unable to compile successfully

**Comment by mjkdz** [comment]
buffer = (unsigned char *)malloc(bytes);

**Comment by tfohlmeister** [comment]
For everyone else stumbling upon this:
I was trying to make this run under PlatformIO and the trick for fixing this error is to add `#include <malloc.h>` on top at `DMABuffer.h`. Compiled just fine afterwards.
